#cloud-config
hostname: lb
ssh_pwauth: true
disable_root: false

users:
  - name: ubuntu
    groups: sudo
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    lock_passwd: false
    ssh_authorized_keys:
      - ssh-rsa AAA <your public key here>
  - name: root
    lock_passwd: false
    shell: /bin/bash

package_update: true
package_upgrade: true
packages:
  - qemu-guest-agent
  - haproxy

bootcmd:
  - sed -i 's/^GRUB_CMDLINE_LINUX=.*/GRUB_CMDLINE_LINUX="console=tty1 console=ttyS0,115200n8"/' /etc/default/grub
  - update-grub
  - systemctl enable serial-getty@ttyS0.service

chpasswd:
  expire: false
  list: |
    root:changeme123

write_files:
  - path: /etc/cloud/cloud.cfg.d/99-disable-network-config.cfg
    permissions: '0644'
    owner: root:root
    content: |
      network: {config: disabled}

  - path: /etc/netplan/01-netcfg.yaml
    permissions: '0600'
    owner: root:root
    content: |
      network:
        version: 2
        ethernets:
          enp1s0:
            dhcp4: false
            dhcp6: false
            addresses: [192.168.1.30/24]
            nameservers:
              addresses: [192.168.1.1,1.1.1.1]
            routes:
              - to: 0.0.0.0/0
                via: 192.168.1.1
          enp2s0:
            dhcp4: false
            dhcp6: false
            addresses: [192.168.6.11/24]

  - path: /etc/haproxy/haproxy.cfg
    permissions: '0644'
    owner: root:root
    content: |
      global
        maxconn 2000
        log /dev/log local0
      defaults
        log     global
        option  tcplog
        timeout connect 10s
        timeout client  1m
        timeout server  1m
      frontend k8s_api
        bind :6443
        default_backend k8s_masters
      backend k8s_masters
        balance roundrobin
        server k8s-cp 192.168.6.10:6443 check

runcmd:
  - rm -f /etc/netplan/50-cloud-init.yaml
  - netplan generate
  - netplan apply
  - systemctl daemon-reload
  - systemctl enable --now qemu-guest-agent
  - systemctl enable --now haproxy

